### ISSUE TITLE
Allow user to choose data file location similar to keepass

### ISSUE THREAD

**Issue by Jim-Young** [TWiStErRob/net.twisterrob.inventory#342] opened 2023-10-05 22:25 UTC
There might be multiple files involved in saved data file as I see the exported file is zipped.

If the data file can be a single one and allow user to choose the location, then it's easier to saved it to cloud drive like google drive or dropbox to save it to share with family members.

It also has lots of potentials. For example, a desktop version for Windows/Linux/macOS could be able to read the data from cloud drive.

**Comment by TWiStErRob** [comment] 2023-10-05 22:27
The latest version already uses the system file chooser, so it should be possible to save wherever you want easily. Can you please make sure your app is up to date and try?

**Comment by Jim-Young** [comment] 2023-10-06 05:51
Hi Rob, it only asks when you try to export and I don't see anywhere you can save as or open data file.

The version I'm using is 1.2.0#1279-8eca619.

**Comment by TWiStErRob** [comment] 2023-10-06 10:00
Ah, ok, it's a duplicate of #56 then, also could help with #53, an interesting idea.

**Closed by TWiStErRob** 2023-10-06 10:00 UTC
Labels: is:duplicate
