### ISSUE TITLE
Search Button always on top & visible

### ISSUE THREAD

**Issue by Jim-Young** [TWiStErRob/net.twisterrob.inventory#341] opened 2023-10-05 22:19 UTC
Thank you Rob for this wonderful app and it's a life saver.

One suggestion, if we could make the Search Button always visible, so when entering/checking 10th nested items, you don't have to press back (←) 10 times or hold ← to go back to home page to search. 

It's not critical but nice to have search button visible all the time. You can search whenever you want.

**Comment by TWiStErRob** [comment] 2023-10-05 22:29
Thanks for the feedback! I was thinking about this myself.

The problem I see is usability: having a search button 5 levels deep. Does it search levels 6-10, or from the top? So simply adding the button could be misleading and implementing nested search could be tricky, but something I want to do anyway atone point.

**Comment by TWiStErRob** [comment] 2023-10-06 10:03
Duplicate of #66

**Closed by TWiStErRob** 2023-10-06 10:03 UTC
Labels: is:duplicate, in:navigation, in:search

**Comment by Jim-Young** [comment] 2023-10-10 06:06
I would say the search button is always for searching the whole inventory. If someone has huge amount of similar items which could lead lots of search result, then they should choose something else like SNIPE-IT.

I can't see the content of #66 as it's in your gmail box.

Anyway, it would be pretty handy with the search all button, whenever you are editing or viewing some items just want to find out something else.
